id = "stan"
name = "Stan"
version = "1.1.0"
schema_version = 1
authors = ["Brian Ward <bward@flatironinstitute.org>"]
description = "Stan language support"
repository = "https://github.com/wardbrian/zed-stan-extension"

[grammars.stan]
repository = "https://github.com/WardBrian/tree-sitter-stan"
commit = "110b2e9296645046019602aac361b18dbd492f7d"
path = "grammars/stan"


[grammars.stanfunctions]
repository = "https://github.com/WardBrian/tree-sitter-stan"
commit = "110b2e9296645046019602aac361b18dbd492f7d"
path = "grammars/stanfunctions"

[language_servers.stan-language-server]
name = "stan-language-server"
languages = ["Stan", "Stan Functions"]
