name: build extension

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch: {}

# only run one copy per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out github
        uses: actions/checkout@v5

      - name: Build
        run: |
          cargo clippy
          cargo fmt --check

